name: Pylint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
           pip install -r requirements-dev.txt


      - name: Run PyLint check
        run: | 
          python -m pylint  --fail-under 10 --limit-inference-results 0 ./slodon
    